apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-bar
  namespace: bar
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sa2ntjulian/lesson-158.git
    targetRevision: Head
    path: environments/staging/second-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNameSpace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
